version: '2.3'

services:
  qryn:
    image: qxip/qryn:bun
    expose:
      - 3100
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=clickhouse1
      - CLICKHOUSE_DB=cloki
      - CLICKHOUSE_AUTH=default:password
      - STORAGE_POLICY=external
      - QRYN_LOGIN=test
      - QRYN_PASSWORD=test
